### ISSUE TITLE
[BUG] Water not being consumed when a waterskin's charges drop to zero

### ISSUE THREAD

**Issue by nolorfin** [roth-michael/FoundryVTT-RestRecovery#177]
**Describe the bug**
The SRD's Waterskin items is not set to be "destroyed on empty", which means that after using it once, it runs out of charges, and when your mod checks if there's water in the PC's inventory, it finds an empty waterskin and ignores it, even though there may be 20 other full waterskins available.

**To Reproduce**
1. Add a number of waterskins to a character. 
2. Set the charges to zero. 
3. Select food and water automation.
4. Apply a new day rest to trigger food and water automation. 
5. The mod assumes the character has no water on his inventory.

**Expected behavior**
If a character has at least one full waterskin, it shouldn't matter if he has another one that's empty.

**Screenshots**
<img width="366" alt="Screenshot 2023-12-24 at 13 29 35" src="https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/72673748/5403497d-b3f0-41b5-9e10-b43fead352b2">

**Setup:**
 - Foundry Version: 11.315
 - System Version: DND5e 2.4.1
 - Rest Recovery Version: 1.5.2
 - Browser & version: Foundry app.

**Comment by Haxxer** [comment]
I cannot reproduce this
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/12858387/3617ed52-5597-4650-8571-6ba9327559eb)

**Comment by Haxxer** [comment]
Make sure your waterskins are set to consumable:
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/12858387/7417185b-b698-4741-94e7-2f35086ea715)

**Comment by JaysonMendoza** [comment]
I suspect you need to make sure your players are using waterskins and rations that are setup correctly. I picked up this mod recently and noticed that all the compendium items you import are not really setup with this automation in mind. There isn't really documentation on how to use this correctly, but I can share what I found out.

Once you install the mod it will add a new section for items on the "Details" tab as Haxxer has shown above. You need to modify the item in the compendium your using to have "Item is Consumable" checked and choose the correct type. 

When Rest Recovery detects a long rest has been initiated, it will scan the actor inventory for items that have those things checked and let you choose from them to sate your water and food requirements. 

The "One charge worth entire day worth" means that if you have configured Rest Recovery to require more than one charge of food or water per day, then any item that has that selected will satisfy the food and/or drink requirement for a single day using only one charge. Otherwise, it will contribute one towards your requirement.
