### ISSUE TITLE
[Request] Integration with AC5e

### ISSUE THREAD

**Issue by Kharmans** [roth-michael/FoundryVTT-RestRecovery#209]
The module **Automated Conditions 5e** from thatlonelybugbear has an automation on Exhaustion and since Rest Recovery has a similar integration with CE, can you make that integration with AC5e too?

https://github.com/thatlonelybugbear/automated-conditions-5e

**Comment by roth-michael** [comment]
For the time being, the CE integration has been disabled (since CE exhaustion is broken on 3.1.2 & 3.2). With this latest update (1.9.0), Rest Recovery has automatic integration with AC5e: If One D&D Exhaustion isn't enabled in Rest Recovery, and exhaustion automation is enabled in AC5e, Rest Recovery will defer to AC5e for its exhaustion handling.
