### ISSUE TITLE
[Request] Macro support and documentation

### ISSUE THREAD

**Issue by BenNelsonNeb** [roth-michael/FoundryVTT-RestRecovery#295]
Macros in Foundry are powerful, especially when combining multiple actions into a single click. As a GM I want to run a macro for the whole team that does a short rest, updates the time, rolls a table, and sends a message. I would do the same for a long rest. 

Please add the ability to run macro related to Rest and Recovery: Specifically the following actions.
Trigger a Short or Long rest for a certain profile for certain party members, and the option for new day or not.

example: Start RestRecovery (type: long, profile: desert, newday: true) Actor(ID1, ID2, ID3)

Add this documentation on the Github site. 

Thanks!

**Comment by roth-michael** [comment]
Apologies for taking so long on this one. What I ended up going with is essentially the same thing that the actual prompt UI uses. So, you won't specify the profile in the argument, you'll use the other API functions to set the current active profile prior to prompting the rest. The format for the first argument you pass into the new function is `"userId-actorId"`, this is because a certain actor may have multiple owners, but you'll only want to prompt one of them. You can grab the latest-used version of that with `game.restrecovery.getActiveProfileData()['prompt-rest-config']`. You can also do some of the logic yourself to build that list of strings as desired. I didn't have it happen automatically because there are scenarios where you may want to select a certain user, not just whoever comes up arbitrarily as the first owner.

**Comment by BenNelsonNeb** [comment]
Awesome. I forgot your newest only works on 4.x. So, I'll have to wait a little bit more for other important modules to catch up before making the switch. I definitely will test once I upgrade. Thanks.
